[Step2] 리뷰 요청 드립니다.
spring-basic-study/openapi pull request #14
Opened 2020-01-16 10:46 UTC by ohtaeg

안녕하세요 에디님 
2주차 완료하여 리뷰 요청 드립니다.
지난 1주차 하면서 git이 꼬여서 github에 commit log도 안남더라구요
그래서 그런지 파일이 제대로 push가 되지 않았네요.
로컬은 해결했지만 아직도 깃헙에는 contribution graph가 변하지 않네요 ㅠㅠ

뒤늦게 1주차 내려받아서 확인해보니 계속 에러가 났었네요 ㅠㅠ 죄송합니다.
이번에는 정말로 해결하여 PR 드립니다 :)

2020-01-23 03:11 UTC, sieunkr requested changes

2020-01-23 03:11 UTC, sieunkr commented on docs/mission2.md
> +    - 설정정보는 application 프로퍼티에 설정해서 불러온다.
@PropertySource ( "classpath : application.properties") 를 사용하셨더라구요. 
근데, Spring Boot 에서는 application.properties 를 바로 읽도록 되는것 같아여.

PropertySource 로 application.pro~ 파일을 가져오도록 하는 부분은 불필요한 구문으로 보이네요.

2020-01-23 03:11 UTC, sieunkr commented on naver-api-executor/src/main/java/me/ohtaeg/application/MovieService.java
> +        Movie searchedMovie = (Movie) searchRepository.search(new Movie(searchWord), Movie.class);
바로 리턴해도 될것 같아요!

2020-01-23 03:11 UTC, sieunkr commented on naver-api-executor/src/main/java/me/ohtaeg/util/PropertyUtils.java
> +public class PropertyUtils {
음..그냥 코딩스타일이 차이인것 같은데요. ^^; 

Utils 클래스는 일반적으로 static 메서드로 구성되어있고, 가능하면 public 생성자를 만들지 않거든요. 
즉, 인스턴스화하지 않는데요. 어쩃든 해당 클래스가 NaverApiProperties 를 주입을 받아야 한다면..

Utils 라는 네이밍을 바꾸는게 좋을까요? (잘 모르겟네요. 중요한건 아니니깐 패스하셔도 됩니다)

2020-01-23 03:11 UTC, sieunkr commented on naver-api-executor/src/main/java/me/ohtaeg/application/BlogService.java
> +        searchedBlog.limit(2);
매직넘버가 들어가 있네요!

2020-01-23 03:11 UTC, sieunkr commented on naver-api-executor/src/main/java/me/ohtaeg/api/ApiController.java
> +        // TODO : refactoring
이번 스텝에서는 넘어가고, Step03 에서 한번 같이 고민해보면 될 것 같아요.

별도의 Service 클래스를 만들어주는게 좋을까요? ^^; (어렵네요..)

2020-01-23 03:11 UTC, sieunkr commented on naver-api-executor/src/main/java/me/ohtaeg/domain/repository/SearchRepository.java
> +    default HttpHeaders getHeader(String id, String secret) {
인터페이스에서 디폴트 메서드에서 httpHeader를 설정해서 제공하는데요. 
특정 API 를 사용하다가, 다른 API 를 변경했을때는 유연하진 않을것 같아요.
(예를 들어서 네이버 오픈 API 를 사용하다가 카카오 오픈 API 로 바꾼다거나..)
 
네이버 오픈 API 에 의존하는 코드가 있어서 조금 애매합니다만.
스터디 중에 오픈API 를 바꿀 생각은 없어서, 중요하진 않은 것 같아요ㅋㅋ

2020-01-23 03:11 UTC, sieunkr commented on naver-api-executor/src/main/java/me/ohtaeg/domain/response/Blog.java
> +    private static class Item {
[질문] Item에 선언된 setter 가 전부 필요할까요? (필요 없을것 같기도 하구요..)
음.. 어쩃든 setter 가 많이 보여서 다 필요한건가 하는 생각에 문의 드렸어용

2020-01-23 03:12 UTC, sieunkr commented
짜잘한(?) 댓글 몇개 남겨놨어요!! 추상화를 심플하게 잘 해주셔서 코드 보면서 배우고 있습니다!!

2020-01-23 06:56 UTC, ohtaeg commented on docs/mission2.md
> +    - 설정정보는 application 프로퍼티에 설정해서 불러온다.
그렇네요! 감사합니다. 다음 PR시 적용하겠습니다 👍

2020-01-23 06:58 UTC, ohtaeg commented on naver-api-executor/src/main/java/me/ohtaeg/application/MovieService.java
> +        Movie searchedMovie = (Movie) searchRepository.search(new Movie(searchWord), Movie.class);
바로 리턴하도록 수정하였습니다. 사소한 코드 스멜 까지 잡아주셔서 감사합니다!

2020-01-23 07:00 UTC, ohtaeg commented on naver-api-executor/src/main/java/me/ohtaeg/util/PropertyUtils.java
> +public class PropertyUtils {
리뷰를 통해 인스턴스를 생성하지 못하도록 변경하였습니다.
게다가 기존 소스를 보니 제가 static 메서드에서 PropertyUtils 인스턴스의 값을 호출하도록 했었네요.
기존에 NaverApiProperties를 static으로 두지않고
PropertyUtils 자체를 싱글톤으로 만들어서 반영하였습니다.

게다가 3주차부터 멀티스레드에 대한 코드가 들어가기 때문에 멀티스레드 환경을 대비해
싱글톤 생성시 LazyHolder 기법을 이용하였습니다.

2020-01-23 07:01 UTC, ohtaeg commented on naver-api-executor/src/main/java/me/ohtaeg/application/BlogService.java
> +        searchedBlog.limit(2);
코드스멜 수정하였습니다 👍

2020-01-23 07:01 UTC, ohtaeg commented on naver-api-executor/src/main/java/me/ohtaeg/api/ApiController.java
> +        // TODO : refactoring
이 부분은 step03에서 고민해보겠습니다!

2020-01-23 07:01 UTC, ohtaeg commented on naver-api-executor/src/main/java/me/ohtaeg/domain/repository/SearchRepository.java
> +    default HttpHeaders getHeader(String id, String secret) {
이 부분 또한 step03에서 고민해보겠습니다!

2020-01-23 07:01 UTC, ohtaeg commented on naver-api-executor/src/main/java/me/ohtaeg/domain/response/Blog.java
> +    private static class Item {
피드백을 통하여 setter를 제거하였으며, 기본생성자 접근제한자도 변경하였습니다.

2020-01-23 07:02 UTC, ohtaeg commented
안녕하세요 에디님 :) 
리뷰주셔서 감사합니다. 리뷰에 대한 피드백을 반영해보았습니다.
꼼꼼하게 리뷰해주셔서 감사할 따름입니다.

최대한 피드백에 맞게 반영해보았습니다 :)

2020-01-26 01:36 UTC, sieunkr commented
역시 너무 잘하시네요!! 코드 리뷰가 아니라, 코드를 보면서 배우는 리뷰 중입니다!!

추가로 고민해야하는 내용들은 STEP03에서 같이 해주시면 좋을 것 같아요.
참고로, STEP03 요구사항은 심플하게 다시 정리했습니다.

2020-01-26 01:36 UTC, merged