Step02 과제 완료했습니다.
spring-basic-study/openapi pull request #15
Opened 2020-01-16 15:39 UTC by hwang11

RestTemplate 쓰레드풀 설정하는 건 미처못했습니다. 비효율적인 코드 같아서 나중에 더 수정해보겠습니다!

2020-01-17 08:51 UTC, sieunkr reviewed
일단, "핵심 요구사항"을 반영하지 못하고 있는것 같은데요. 

검색 조건에 맞는 검색 결과를 제대로 못하고 있어서요. 
그부분 해결되시고 다시 수정 PUSH 해주시면 추가로 리뷰해볼게요.

그리고, 기초가 부족하신것 같으니 책한권 추천해드릴게요.
http://www.yes24.com/Product/Goods/83849117
이 책 5장까지만 먼저 보시면 될것 같아요. (6장 부터는 AWS관련 내용이라서 나중에 보셔도 됩니다)

2020-01-17 08:51 UTC, sieunkr commented on src/main/java/com/example/openapi/controller/HomeController.java
> +    public SearchResponse blogSearch(String query){
STEP01 에서 제가 커멘트 남겼었는데요, 처리가 안된것 같아요. 
블로그, 영화 등 검색조건에 맞는 데이터를 검색해야 하는데요. 

public SearchResponse search(String url, String text,Class<? extends SearchResponse> responseType){
text 에 null 이 들어가요. 

@GetMapping("/blog")
    public SearchResponse blogSearch(@RequestParam(name = "query") String query ){

이런식으로 변경하고, 

/api/blog?query=겨울왕국2 
으로 호출했을 때, 겨울왕국2에 맞는 블로그 정보가 조회되는지까지 확인부탁드릴게요!! (현재 코드는 null 이 들어가기 때문에 엉뚱한 검색결과가 조회되네요)

2020-01-17 08:51 UTC, sieunkr commented on src/main/java/com/example/openapi/controller/HomeController.java
> +    static final int LIMIT = 5;
private 으로 변경해주시고, 의미있는 상수명으로 변경해주시면 좋을 것 같아요. 
예를 들어서, 
LIMIT_ITEM_COUNT 등으로요.

2020-01-17 08:51 UTC, sieunkr commented on src/main/java/com/example/openapi/controller/HomeController.java
> +        BlogSearchResponse blogSearchResponse = (BlogSearchResponse) searchService.search(searchProperties.getBlogUrl(), query, BlogSearchResponse.class);
Controller 에서 수행하는 코드가 좀 길어서요. 리팩토링 해주시면 좋을 것 같은데요. 

일단, 통합검색(영화, 블로그 )등의 정보를 취합해주는 신규 Service 클래스를 만들어보시는건 어떠신가요?

2020-01-17 08:51 UTC, sieunkr commented on src/main/java/com/example/openapi/config/ApiConfiguration.java
> +        CloseableHttpClient client = HttpClientBuilder.create().setMaxConnTotal(50).setMaxConnPerRoute(20).build();
CloseableHttpClient client = 
는 사용하지 않는 구문인데요. 일단, 불필요한 구문은 삭제해주시면 좋을것 같아요.

2020-01-17 08:51 UTC, sieunkr commented on src/main/java/com/example/openapi/controller/HomeController.java
> +        for(int i=0;i<LIMIT;i++){
Java 8 Stream API 로 변경해보시는건 어떠신가요?
아래 코드가 동작하는지는 확인은 못했습니다만, 

movieItems.addAll(movieSearchResponse.getItems().stream().limit(LIMIT).collect(Collectors.toList()));

어쨋든, for문 또는 if 문으로 작성하는 "명령형 프로그래밍" 보다는 
함수형 프로그래밍 에 맞게 코드를 짜보시는것도 도움이 되실것 같아요. 

(Stream 익숙하지 않으시면 "모던 자바 인 액션" 이라는 책을 보시면 도움이 됩니다.)

2020-01-17 08:53 UTC, sieunkr reviewed
STEP02 코드리뷰 결과 공유 드립니다!!

2020-01-19 12:46 UTC, hwang11 commented
> 일단, "핵심 요구사항"을 반영하지 못하고 있는것 같은데요.
> 
> 검색 조건에 맞는 검색 결과를 제대로 못하고 있어서요.
> 그부분 해결되시고 다시 수정 PUSH 해주시면 추가로 리뷰해볼게요
> 
> 그리고, 기초가 부족하신것 같으니 책한권 추천해드릴게요.
> http://www.yes24.com/Product/Goods/83849117
> 이 책 5장까지만 먼저 보시면 될것 같아요. (6장 부터는 AWS관련 내용이라서 나중에 보셔도 됩니다)

감사합니다! 저도 부족함을느껴 그 책을 구비해서 보기시작했습니다! 5장까지 잘 살펴보겠습니다. 리뷰남겨 주신것도 얼른 수정해서 push하도록 하겠습니다 감사합니다!

2020-01-20 07:43 UTC, hwang11 commented on src/main/java/com/example/openapi/config/ApiConfiguration.java
> +        CloseableHttpClient client = HttpClientBuilder.create().setMaxConnTotal(50).setMaxConnPerRoute(20).build();
아 이부분에 대한 이해가 부족해서 불필요한 부분인줄 몰랐네요 ㅠㅠ factory의 역할은 restTemplate의 설정을 지정해주는 건가요? 이부분 잘 이해가 안되는데 혹시 추천해주실만한 글이 있으실까요?
제가 그나마 본 블로그는 https://ddoriya.tistory.com/entry/RestTemplate-%EC%A0%95%EC%9D%98-%ED%8A%B9%EC%A7%95-URLConnection-HttpClient-%EB%8F%99%EC%9E%91%EC%9B%90%EB%A6%AC-%EC%82%AC%EC%9A%A9%EB%B2%95-connection-pool-%EC%A0%81%EC%9A%A9?category=571371 였는데 
'ClientHttpRequestFactory 로 부터 ClientHttpRequest 를 가져와서 요청을 보낸다.' 라는 것 외에 별다른 설명이 없는것같아서요..

2020-01-20 07:43 UTC, hwang11 commented on src/main/java/com/example/openapi/controller/HomeController.java
> +        for(int i=0;i<LIMIT;i++){
통합검색 Service 클래스를 만들고 Stream을 이용해서 변경했습니다!

2020-01-20 07:46 UTC, hwang11 commented
restTemplate의 쓰레드풀을 설정은 ExecutorService를 사용하는 건지 궁금합니다! 그리고 리뷰 감사드립니다 과제도 알차서 정말 도움이 많이됩니다!!

2020-01-22 13:45 UTC, sieunkr requested changes
일단, 애플리케이션 정상적으로 실행되는지 한번더 확인해주시면 그 이후 다시 리뷰를 진행할게요.

개인적인 생각이지만.. build.gradle 설정을 변경하신 후, refresh 를 안하신거 같다는 추측(?) 입니다만, 
즉, 본인 pc 에서는 잘 실행되지만, 다른 사람(저) 가 프로젝트를 처음 다운받아서 실행해보면 안될 수도 있을 것 같아요..

일단 gradle refresh 해보시구요. 이상하다 생각되시면 다시 코멘트 남겨주세요.

2020-01-22 13:45 UTC, sieunkr commented on .gitignore
> +application.properties
일반적으로 application.properties 파일은 ignore 로 빼지는 않습니다.
(application-local.properties 는 개발 환경에 따라서 빼는 경우도 종종 있지만..)

근데, 파일을 delete 해서 푸쉬를 해주셨네요. 일단, 해당 파일은 다시 살려주시는게 좋을 것 같아요.

(아니면 혹시 인증키 때문에 매번 제외하고 커밋하는게 불편해서 ignore 처리를 하신걸까요?)

2020-01-22 13:45 UTC, sieunkr commented on build.gradle
> +dependencies { //프로젝트 개발에 필요한 의존성들 선언
혹시 디펜던시 변경하고.. gradle refresh 해보셨나요? 
디펜던시를 언제하신건지는 모르겠습니다만 

step02 코드 제 로컬에서 실행해보면 실행이 잘 안되네요ㅠㅠ

2020-01-22 14:51 UTC, hwang11 commented
지금 바로 수정해봤습니다. build.gradle 수정 이후에 dependency에서 httpclient 부분을 삭제해서 그런 것 같습니다.

2020-01-22 14:53 UTC, hwang11 commented on .gitignore
> +application.properties
인증키때문에 제외하려고 했던 것 맞습니다 ㅠㅠ 프로젝트 외부로 별도의 파일을 생성해서 빼려고 했는데 우선 push할 때는 application.properties만 없으면 되지 않을까해서 제외했었습니다. ㅠㅠ

2020-01-23 00:59 UTC, sieunkr requested changes
리뷰 했습니다. 한번의 PR 에 리뷰를 여러번 하니 댓글이 많아져서 헷깔리네요. 
이번건만 수정되면 바로 머지할게요!! ^^

2020-01-23 00:59 UTC, sieunkr commented on src/main/java/com/example/openapi/config/ApiConfiguration.java
> +        factory.setConnectTimeout(10*1000); //몇초가 적당한 시간인지?
application.properties 에 속성값을 정의하고
@value 어노테이션으로 가져와서 적용해주는게 좋을것 같아요!

https://betterfly88.github.io/dev/spring_9/

2020-01-23 00:59 UTC, sieunkr commented on src/main/java/com/example/openapi/repository/Movie.java
> +public class Movie extends Result {
블로그 정보 조회랑 비교했을 때 영화 정보는 

private int total;
private int start;
private int display;

를 선언하진 않으셨네요? 

근데, 해당 필드가 공통 필드가 확실하다면..
즉, 네이버 오픈 API에서 제공하는 스펙에서 해당 필드가 공통으로 제공한다면

만들어주신 추상클래스에 선언해도 될 것 같아요. 

@Getter
public abstract class Result {
    private int total;
    private int start;
    private int display;
}

요렇게요. 추상클래스에 정의한다면, 상속받는 Blog 에 선언하신건 지워도 되구요.

2020-01-23 00:59 UTC, sieunkr commented on src/main/java/com/example/openapi/config/ApiConfiguration.java
> +    public RestTemplate restTemplate(){ //질문
RestTemplate은 디폴트 생성자 외에 ClientHttpRequestFactory 인터페이스를 받는 생성자가있는데요. 
그 중 SimpleClientHttpRequestFactory와 HttpComponentsClientHttpRequestFactory가 대표적인 구현체라고 하네요. 어떻게 동작하는지는... 저도 소스를 까봐야할 것 같아요ㅠㅠ 

사용하신 HttpComponentsClientHttpRequestFactory 에 

HttpClient httpClient = HttpClientBuilder.create() 
        .setMaxConnTotal(100) // 최대 커넥션 갯수
        .setMaxConnPerRoute(5) // IP/domain name당 최대 커넥션 갯수 
        .build(); 
factory.setHttpClient(httpClient);

이런식으로 하시면 되지 않을까 하는 생각입니다. (질문 주신 executorservice 를 사용해서 직접 구현할 필요는 없어요)

2020-01-24 14:50 UTC, hwang11 commented on src/main/java/com/example/openapi/repository/Movie.java
> +public class Movie extends Result {
아 영화 검색 API에서 돌려주는 값 중에는 total,start,display가 없어서 추가하지 않았습니다! 후에 공통적인 멤버필드가 생기면 추상클래스에 선언하도록 하겠습니다!

2020-01-24 14:50 UTC, hwang11 commented on src/main/java/com/example/openapi/config/ApiConfiguration.java
> +        factory.setConnectTimeout(10*1000); //몇초가 적당한 시간인지?
application.properties를 프로젝트 외부로 빼고 @value 어노테이션으로 값을 가져오도록 수정했습니다!

2020-01-24 14:54 UTC, hwang11 commented on src/main/java/com/example/openapi/config/ApiConfiguration.java
> +    public RestTemplate restTemplate(){ //질문
아 감사합니다! 음 그런데 과제에 쓰레드풀을 설정해보라고 하셨는데 커넥션 개수를 설정하는 것이 쓰레드풀을 설정하는것 인가요?

2020-01-26 01:30 UTC, sieunkr commented on src/main/java/com/example/openapi/repository/Movie.java
> +public class Movie extends Result {
아!! 그렇군요. 제가 스펙을 자세히 안봐서 몰랐네요 ㅠㅠ 

그런데, 공통멤버 없으면 추상클래스 상속을 안받는게 좋을 것 같아요!!

2020-01-26 01:31 UTC, merged

2020-01-26 01:33 UTC, sieunkr commented on src/main/java/com/example/openapi/config/ApiConfiguration.java
> +    public RestTemplate restTemplate(){ //질문
네!! 맞습니다! 과제 설명이 친절하지 않았네요ㅠ 죄송...ㅠㅠ

2020-01-28 06:53 UTC, hwang11 commented on src/main/java/com/example/openapi/repository/Movie.java
> +public class Movie extends Result {
넵 알겠습니다!

2020-01-28 06:54 UTC, hwang11 commented on src/main/java/com/example/openapi/config/ApiConfiguration.java
> +    public RestTemplate restTemplate(){ //질문
아 그렇군요 감사합니다!!